### ISSUE TITLE
Error unmarshalling API response: unexpected end of JSON input

### ISSUE THREAD

**Issue by nourserry** [imthaghost/scdl#4]
got this today trying to download, did soundcloud change their API?

```
'/home/photon/go/bin/scdl' https://soundcloud.com/otteswed/ucs6tqxvrmel
ملايكة °نسخة الفيديو
[-] Error unmarshalling API response: unexpected end of JSON input
[-] Parse m3u8 file failed: Get "": unsupported protocol scheme ""
[+] Will save to ملايكة °نسخة الفيديو.mp3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x751bd6]

goroutine 1 [running]:
github.com/grafov/m3u8.(*MediaPlaylist).Count(...)
	/home/photon/go/pkg/mod/github.com/grafov/m3u8@v0.11.1/writer.go:727
github.com/imthaghost/scdl/mp3.Merge(0x0, 0x0, 0xc0000ac5a0, 0x26)
	/home/photon/go/src/github.com/imthaghost/scdl/mp3/merge.go:235 +0x516
github.com/imthaghost/scdl/soundcloud.ExtractSong(0x7ffe8be452a6, 0x2c)
	/home/photon/go/src/github.com/imthaghost/scdl/soundcloud/song.go:80 +0x4b3
github.com/imthaghost/scdl/cmd.scdl(0xc000098e80, 0x1, 0x1)
	/home/photon/go/src/github.com/imthaghost/scdl/cmd/base.go:17 +0x65
github.com/imthaghost/scdl/cmd.glob..func1(0xb40f00, 0xc000098e80, 0x1, 0x1)
	/home/photon/go/src/github.com/imthaghost/scdl/cmd/root.go:31 +0xac
github.com/spf13/cobra.(*Command).execute(0xb40f00, 0xc0000a8030, 0x1, 0x1, 0xb40f00, 0xc0000a8030)
	/home/photon/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xb40f00, 0xb8d14a, 0x870463, 0x6)
	/home/photon/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/photon/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/imthaghost/scdl/cmd.Execute()
	/home/photon/go/src/github.com/imthaghost/scdl/cmd/root.go:43 +0x9f
main.main()
	/home/photon/go/src/github.com/imthaghost/scdl/main.go:6 +0x25

```

**Comment by imthaghost** [comment]
See issue #6
